# Behavioural test for dev shell project detection — flake.nix, host-side runner.
#
# Issue #19: `devenv init` writes devenv.nix, devenv.yaml and .gitignore, while
# the gate looked for flake.nix or .devenv.flake.nix. A project created the way
# devenv's own guide describes matched neither, so DIRENV_ALLOW=1 silently did
# nothing. A fixture list written from the same assumption that produced the bug
# would have agreed with it, so the first fixture here is generated by running
# the real `devenv init` inside the build sandbox: if devenv changes its
# conventions again, this goes red for the same reason #19 was filed.
#
# The region is extracted from the *built* runner rather than from flake.nix, so
# the Nix-to-shell escaping is covered too. It is detection only — no evaluation
# and no side effects, which is what makes it safe to source here, and the test
# also pins that it stays nested inside the DIRENV_ALLOW check.
{ pkgs, lib, runner }:

pkgs.runCommand "devshell-detection" { nativeBuildInputs = [ pkgs.devenv ]; } ''
  export HOME=$TMPDIR/home
  mkdir -p "$HOME" "$TMPDIR/fx"
  cd "$TMPDIR"

  script=${runner}/bin/microvm-run
  awk '/# BEGIN devshell-detect/{f=1;next} /# END devshell-detect/{f=0} f' "$script" > detect.sh
  if [ ! -s detect.sh ]; then
    echo "FAIL: no detection region found in the runner — did the markers move?" >&2
    exit 1
  fi

  fail=0
  ok ()  { echo "ok: $1"; }
  bad () { echo "FAIL: $1" >&2; fail=1; }

  # Reaching detection without DIRENV_ALLOW=1 is what would put
  # `nix print-dev-env` on the host against an untrusted $WORK.
  if grep -B 20 '# BEGIN devshell-detect' "$script" | grep -q 'DIRENV_ALLOW:-0.*= "1"'; then
    ok "detection stays nested inside the DIRENV_ALLOW gate"
  else
    bad "detection is no longer guarded by DIRENV_ALLOW"
  fi

  # label, dir, expected eligibility, expected command
  expect () {
    got=$( export WORK="$2"; . ./detect.sh; echo "$_DEVSHELL_ELIGIBLE|$_CACHE_CMD" )
    want="$3|$4"
    if [ "$got" = "$want" ]; then
      ok "$1"
    else
      bad "$1: got [$got], wanted [$want]"
    fi
  }

  # The fixture that would have caught #19: whatever devenv actually writes.
  mkdir -p fx/real && (cd fx/real && devenv init)
  echo "--- devenv init produced: $(cd fx/real && ls -A | tr '\n' ' ')"
  expect "a stock \`devenv init\` project is recognised" \
    "$TMPDIR/fx/real" 1 "devenv print-dev-env"

  mkdir -p fx/flake && touch fx/flake/flake.nix
  expect "a plain flake uses nix print-dev-env" \
    "$TMPDIR/fx/flake" 1 "nix print-dev-env --no-update-lock-file $TMPDIR/fx/flake"

  mkdir -p fx/both && touch fx/both/flake.nix fx/both/devenv.nix
  expect "flake.nix plus devenv.nix goes through --impure" \
    "$TMPDIR/fx/both" 1 "nix print-dev-env --no-update-lock-file --impure $TMPDIR/fx/both"

  mkdir -p fx/legacy && touch fx/legacy/.devenv.flake.nix
  expect "the legacy .devenv.flake.nix layout still works" \
    "$TMPDIR/fx/legacy" 1 "devenv print-dev-env"

  mkdir -p fx/none && touch fx/none/README.md
  expect "a directory with neither marker is not eligible" \
    "$TMPDIR/fx/none" 0 ""

  [ "$fail" -eq 0 ] || exit 1
  touch $out
''
